development:
  adapter: postgresql
  encoding: unicode
  database: myproductexpiryapp_development
  pool: 5
  username: myproductexpiryapp
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: myproductexpiryapp_test
  pool: 5
  username: myproductexpiryapp
  password: password
