# This file was automatically generated by weform 0.53.0. Do not edit it
# manually.

locals {
  service    = "product-expiry-manager"
  costcenter = "analyse_and_transform"
}

variable aws_profile {
  default = "wetransfer-users-mfa"
}

variable assumed_role {
  default = "platform"
}
