# This file was automatically generated by weform 0.53.0. Do not edit it
# manually.

# This assumes local.service is defined by the scaffolding setup in the application
locals {
  aws_accounts = {
    ci    = 547242655233
    dev   = 910225604157
    stag  = 421783656539
    prod  = 724500836836
    plat  = 747772944961
    users = 470120686649
  }

  full_account_names = {
    ci    = "integration"
    dev   = "development"
    stag  = "staging"
    prod  = "production"
    plat  = "platform"
    users = "users"
  }

  # The .com domains for each environment. CI uses the same domain as staging.
  # And plat uses the same as prod.
  tlds = {
    ci    = "wetransferbeta.com"
    dev   = "wetransferalpha.com"
    stag  = "wetransferbeta.com"
    prod  = "wetransfer.com"
    plat  = "wetransfer.com"
    users = "wetransfer.com"
  }

  # The .net domains for each environment. CI uses the same domain as staging.
  # And plat uses the same as prod.
  net_tlds = {
    ci    = "wetransferbeta.net"
    dev   = "wetransferalpha.net"
    stag  = "wetransferbeta.net"
    prod  = "wetransfer.net"
    plat  = "wetransfer.net"
    users = "wetransfer.net"
  }

  # Strip the region of the workspace so we can append the region when needed.
  workspace = replace(terraform.workspace, "/-(${join("|", keys(local.region_map))})$/", "")

  region_map = {
    euwest1 = "eu-west-1"
    useast1 = "us-east-1"
  }

  region = "${lookup(local.region_map, reverse(split("-", terraform.workspace))[0], "eu-west-1")}"

  # local.workspace can be "ci-adsasdasd" and local.workspace_prefix will return "ci"
  workspace_prefix_regex_search = "/^(${join("|", keys(local.aws_accounts))})-.*/"
  workspace_prefix              = replace(local.workspace, local.workspace_prefix_regex_search, "$1")

  # Account number based on workspace_prefix, no default since being explicit is better than
  # choosing a default workspace account as a catch-all
  workspace_account = local.aws_accounts[local.workspace_prefix]

  aws_region_no_hyphens = replace(local.region, "-", "")
  prefix                = "wt-${local.workspace}-${local.aws_region_no_hyphens}-${local.service}"
  prefix_for_tags       = "wt-${local.workspace}-${local.aws_region_no_hyphens}"
  short_prefix          = "wt-${local.workspace}-${local.service}"

  # ECR
  ecr_account_name = "plat"
  ecr_account_id   = lookup(local.aws_accounts, local.ecr_account_name)
  ecr_role_name    = local.workspace_prefix == "dev" ? local.service : "platform"

  # Route53 / ACM
  wetransfer_tld     = local.tlds[local.workspace_prefix]
  wetransfer_net_tld = local.net_tlds[local.workspace_prefix]

  common_tags = {
    costcenter  = local.costcenter
    environment = local.workspace_prefix
    service     = local.service
    tfworkspace = local.workspace
  }

  common_asg_tags = [
    {
      key                 = "costcenter"
      value               = local.common_tags["costcenter"]
      propagate_at_launch = true
    },
    {
      key                 = "environment"
      value               = local.common_tags["environment"]
      propagate_at_launch = true
    },
    {
      key                 = "service"
      value               = local.common_tags["service"]
      propagate_at_launch = true
    },
    {
      key                 = "tfworkspace"
      value               = local.common_tags["tfworkspace"]
      propagate_at_launch = true
    }
  ]

  aws_users_account = "470120686649"

  is_non_standard_aws_account = local.workspace_prefix == "users" || local.workspace_prefix == "plat"
  vpc_tags_prefix             = local.is_non_standard_aws_account ? "prod" : local.workspace_prefix

  # Below are locals that should be considered private and used within
  # weform-generated files only. If you choose to depend on them, you are
  # risking backwards compatibility issues.

  __weform_data_source_account_id = local.is_non_standard_aws_account ? local.aws_accounts["prod"] : local.aws_accounts[local.workspace_prefix]
}
